apiVersion: v1
kind: ConfigMap
metadata:
  name: guacamole-configuration
  labels:
    app.kubernetes.io/name: guacamole
    {{- include "guacamole-stack.labels" . | nindent 4 }}
data:
  guacamole.properties: |
    enable-environment-properties: true
    postgresql-auto-create-accounts: true
