apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: guacamole-pg-credentials
  labels:
    {{- include "guacamole-stack.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: guacamole-pg-credentials
  data:
    - secretKey: password
      remoteRef:
        key: {{ .Values.vaultPgPath }}
        property: pg-password
    - secretKey: postgres-password
      remoteRef:
        key: {{ .Values.vaultPgPath }}
        property: pg-password
