apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgresql-credentials
  namespace: utility
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: postgresql-credentials
  data:
    - secretKey: postgres-password
      remoteRef:
        key: secret/data/postgresql
        property: postgres-password
    - secretKey: metadata-user-password
      remoteRef:
        key: secret/data/postgresql
        property: metadata-user-password
    - secretKey: project-user-password
      remoteRef:
        key: secret/data/postgresql
        property: project-user-password
    - secretKey: auth-user-password
      remoteRef:
        key: secret/data/postgresql
        property: auth-user-password
    - secretKey: dataops-user-password
      remoteRef:
        key: secret/data/postgresql
        property: dataops-user-password
    - secretKey: notification-user-password
      remoteRef:
        key: secret/data/postgresql
        property: notification-user-password
    - secretKey: dataset-user-password
      remoteRef:
        key: secret/data/postgresql
        property: dataset-user-password
    - secretKey: approval-user-password
      remoteRef:
        key: secret/data/postgresql
        property: approval-user-password
