apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jupyterhub-keycloak
  labels:
    {{- include "jupyterhub-stack.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: jupyterhub-keycloak
  data:
    - secretKey: KEYCLOAK_CLIENT_ID
      remoteRef:
        key: secret/data/jupyterhub/{{ .Values.projectName }}
        property: keycloak-client-id
    - secretKey: KEYCLOAK_CLIENT_SECRET
      remoteRef:
        key: secret/data/jupyterhub/{{ .Values.projectName }}
        property: keycloak-client-secret
