apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-tools
  labels:
    {{- include "project-resources.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 1Gi
