apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-backup
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: vault-backup
spec:
  schedule: "0 2 * * *"  # Daily at 2 AM
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          securityContext:
            runAsNonRoot: true
            runAsUser: 100
            runAsGroup: 1000
            fsGroup: 1000
            seccompProfile:
              type: RuntimeDefault
          containers:
            - name: backup
              image: alpine:3.19
              resources:
                requests:
                  memory: 32Mi
                  cpu: 10m
                limits:
                  memory: 128Mi
                  cpu: 100m
              securityContext:
                allowPrivilegeEscalation: false
                readOnlyRootFilesystem: true
                capabilities:
                  drop:
                    - ALL
              command:
                - /bin/sh
                - -c
                - |
                  set -e
                  TIMESTAMP=$(date +%Y%m%d-%H%M%S)
                  BACKUP_DIR=/backup/${TIMESTAMP}
                  mkdir -p ${BACKUP_DIR}
                  cp -a /vault/data/* ${BACKUP_DIR}/
                  # Keep only last 7 backups
                  cd /backup && ls -t | tail -n +8 | xargs rm -rf || true
                  echo "Backup completed: ${BACKUP_DIR}"
              volumeMounts:
                - name: vault-data
                  mountPath: /vault/data
                  readOnly: true
                - name: vault-backup
                  mountPath: /backup
          volumes:
            - name: vault-data
              persistentVolumeClaim:
                claimName: data-vault-0
            - name: vault-backup
              persistentVolumeClaim:
                claimName: vault-backup
