apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-credentials
  namespace: minio
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: minio-credentials
  data:
    # Auth credentials
    - secretKey: root-user
      remoteRef:
        key: secret/data/minio
        property: access_key
    - secretKey: root-password
      remoteRef:
        key: secret/data/minio
        property: secret_key
    # Encryption master key (format: key-name:base64-key)
    - secretKey: kms-secret-key
      remoteRef:
        key: secret/data/minio
        property: kms_secret_key
