apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: access-token-public
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: access-token-public
  dataFrom:
    - extract:
        key: secret/data/github-runner
