apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-postgresql-credentials
  namespace: keycloak
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: keycloak-postgresql-credentials
  data:
    - secretKey: postgres-password
      remoteRef:
        key: secret/data/keycloak
        property: postgres-password
    - secretKey: password
      remoteRef:
        key: secret/data/keycloak
        property: keycloak-user-password
