apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: redis-credentials
  namespace: redis
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: redis-credentials
  data:
    - secretKey: password
      remoteRef:
        key: secret/data/redis
        property: password
